### ISSUE TITLE
Encapsulator hangs on R scripts without inputs

### ISSUE THREAD

**Issue by margoseltzer** [ProvTools/encapsulator#23]
We tried running encapsulator on A) and R script that is just a function; since nothing runs, encapsulator seems to just hang, even with encapsulate --info, B) And if the script only plots, it also seems to hang.

I think nicer behavior might be a message telling the user what's wrong (no output found).

**Comment by MKLau** [comment]
Thanks Margo. If you would, drop the R script into this thread so we can use it to test.

**Comment by cscn** [comment]
[encap_test.zip](https://github.com/ProvTools/encapsulator/files/1783095/encap_test.zip)

This file (from the provided test cases in the repo) seemed to hang while running locally on my computer using the gem install version of encapsulator.

**Comment by MKLau** [comment]
Great, thanks Chris. I'll take a look.

**Comment by MKLau** [comment]
@cscn 

Chris, were you able to run encapsulator on encapsulator/examples/messycode.R? When I run ```encapsulator --info messycode.R``` on my machine in this directory, it runs without error and returns results.

**Comment by cscn** [comment]
this is what it looks like from my command line
`chrischen-C02Q72APG8WL:example chrischen$ encapsulator --info messycode.R`

**Comment by cscn** [comment]
`chrischen-C02Q72APG8WL:example chrischen$ ps aux | grep -r encap
(standard input):chrischen        83966   0.0  0.0  4304016   2264 s004  S     5:26PM   0:00.07 /Users/chrischen/.rbenv/versions/2.0.0-p647/bin/ruby /Users/chrischen/.rbenv/versions/2.0.0-p647/bin/encapsulator --info messycode.R
(standard input):chrischen        88750   0.0  0.0  4267768    888 s010  S+    8:02PM   0:00.00 grep -r encap
(standard input):chrischen        86654   0.0  0.1  4329616   9632 s002  S+    7:47PM   0:00.10 /Users/chrischen/.rbenv/versions/2.0.0-p647/bin/ruby /Users/chrischen/.rbenv/versions/2.0.0-p647/bin/encapsulator --info messycode.R`

The code has been running for over 15 minutes now, and still hasn't generated results.

**Comment by MKLau** [comment]
Ah, ok. So all of the messycode.R dependencies should be there. Let me try on another machine and see what I get.

**Comment by MKLau** [comment]
Also, let's see what Thomas says. 

@tfjmp

**Comment by tfjmp** [comment]
That has been a very long time, and encapsulator was a proof of concept we put together quickly for a submission. Excitement/interest in it faded quickly so I would really not assume the code to be anything close to robust or production ready.

Issues that may exist:

static definition of a bunch of stuff
https://github.com/ProvTools/encapsulator/blob/master/lib/encapsulator/installer.rb#L4
https://github.com/ProvTools/encapsulator/blob/master/lib/encapsulator/cli.rb#L20
https://github.com/ProvTools/encapsulator/blob/master/lib/encapsulator/provr.rb#L8

In particular the last one may break things, if the code have changed. What should probably be changed is to point to a specific version of ProvR/RDataTracker.

The provenance graph need to be correct, I don't guarantee what happens if a graph is not complete/well connected.

On the other end, the code is very small and simple, so it should not be too difficult to understand why and where it is hanging. Easy first thing to check, does the json file exist?  If not issue is somewhere in there:
https://github.com/ProvTools/encapsulator/blob/master/lib/encapsulator/provr.rb#L3

If yes, then the issue occurs during the parsing:
https://github.com/ProvTools/encapsulator/blob/master/lib/encapsulator/provjson_parser.rb#L55
https://github.com/ProvTools/encapsulator/blob/master/lib/encapsulator/rjson_parser.rb

If it was workig for Messycode example size, it should be nearly instantaneous to get the results.

Also there is some required dependencies, on Mac:
```
encapsulator --install mac
```
I only tested Linux one, Matt tried the mac version.  Although, it does not do much:
https://github.com/ProvTools/encapsulator/blob/master/lib/encapsulator/installer.rb#L14

Also can you confirm what are the platform R version/Ruby version/ProvR/RDataTracker etc... version. If it works for Matt, and not on other machine, it may be some dependencies issue (ironic I know ;-) )

Finally something we were supposed to do for ProvR/RDataTracker/Encapsulator was to build proper continuous integration with a large number of scripts to ensure things were working correctly. No one went around building that corpus of scripts to test our things on. 
https://github.com/ProvTools/cleanR/issues/9
https://github.com/ProvTools/cleanR/issues/10

There is not much details in the issue though ;-). However, ProvR/RDataTracker/Encapsulator are absolutely not close to production ready and will break within months and are very very prone to code rote. If no one is touching them and version of things are changing, they will break done.

**Comment by cscn** [comment]
Also, if it helps, here's the error output when I quit the hanged command: 
```
chrischen-C02Q72APG8WL:example chrischen$ encapsulator --info messycode.R
^[[A^C^C^C^C/Users/chrischen/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/encapsulator-0.1.0/lib/encapsulator/provr.rb:28:in `chdir': No such file or directory - messycode_ddg (Errno::ENOENT)
	from /Users/chrischen/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/encapsulator-0.1.0/lib/encapsulator/provr.rb:28:in `run_script'
	from /Users/chrischen/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/encapsulator-0.1.0/lib/encapsulator/cli.rb:110:in `info'
	from /Users/chrischen/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/encapsulator-0.1.0/bin/encapsulator:6:in `<top (required)>'
	from /Users/chrischen/.rbenv/versions/2.0.0-p647/bin/encapsulator:23:in `load'
	from /Users/chrischen/.rbenv/versions/2.0.0-p647/bin/encapsulator:23:in `<main>'
```

**Comment by cscn** [comment]
Based on this it looks like I have to pre-generate the provenance?

**Comment by MKLau** [comment]
@cscn  @tfjmp Thanks for the input and good points on software support/use, Thomas. This has been a perpetual chicken and egg situation. The cleanR testing for this is not direclty related, but I see what you’re saying in a general sense (though those issues are definitely outstanding). A product of Chris’s work will be extensive testing of catpure systems and encapsulator across many scripts (although, not multiple systems). And, It seems worthwhile to try and debug for Chris’s system, but It may be that it’s not robust enough, given the speed with which it got built and subsequent disuse, and perhaps it should serve as an inspiration for something new. 

Chris, I’ve been in meetings yesterday and this morning and haven’t had a chance yet to run this on another machine. I’ll have an opportunity after lunch today. Also, not sure what the storms going to do, but I’m happy to meet up and work things through and strategize.

**Comment by MKLau** [comment]
Hey Chris, I got this warning while setting up a test on Odyssey. 

“WARNING: ruby-2.0.0-p647 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.“

You might update your Ruby version if you get a chance.

**Comment by MKLau** [comment]
https://www.rc.fas.harvard.edu/resources/documentation/software-on-odyssey/ruby/

Here’s some useful info on how to setup your environment on Odyssey for using Ruby and gem.

**Comment by tfjmp** [comment]
```
git clone https://github.com/ProvTools/encapsulator.git
cd encapsulator
git checkout dev
rake install
encapsulator --version
```

Verify the version is now `0.1.1`.

Let me know if it still hanging on that version. If that fixes the issue, I will publish the gem for version `0.1.1`.

**Comment by tfjmp** [comment]
@MKLau sorry if I sounded overly negative, I was on the move and typed in a bit of a rush ;-). I think I fixed the issue, but would appreciate some Mac people to confirm it works on that config too.

**Comment by MKLau** [comment]
@tfjmp No worries, your points are totally valid, and the reality check is a good one. If no one's using the project (i.e. folks like me), no one has motivation to work on it! 

Thanks for pushing those changes. Chris and I are working on updating his Ruby version, which might have been a source of issues too. Will post results soon.

**Comment by michael-hahn** [comment]
@tfjmp @MKLau @cscn Just followed Thomas's instructions and tried to run the version `0.1.1` on `messycode.R` by:
`sudo encapsulator --info messycode.R `

The execution hangs at one point for a while, though I am not sure if it's actually done:
```
* installing *source* package ‘devtools’ ...
** package ‘devtools’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (devtools)
```

**Comment by MKLau** [comment]
@michael-hahn 

Sweet, thanks Michael.

Similar here. My rake install works (I see v0.1.1) and --info just finished running. Took under 3 minutes.I get some weird POSIX warning, but that's unrelated. 

```
hermes:example hermes$ encapsulator --info messycode.R 
* installing *source* package ‘provR’ ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'zone/tz/2018c.1.0/zoneinfo/America/New_York'
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (provR)
Files
-----
Input sourced.R
Input july_biomass_survey.csv
Input dataset_v2_june_from_collaborator1.csv
Output save1.csv
Output table_2.txt
Output fig1_biplot.png
Output fig1_biplot_t2.png
Output fig2_biplot.png


Packages
--------
base v3.4.2
gdata v2.18.0
lattice v0.20-35
permute v0.9-4
txtplot v1.0-3
vegan v2.4-6
```

*My Machine*
Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017 
MacOS 10.13.3 (17D102)
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16] 
encapsulator 0.1.1

**Comment by tfjmp** [comment]
If you have a "fresh" R environment it takes a while the first time as it installs some R libraries. I don't know on Mac, but on Linux it even goes through compiling some if it. Could it be that, that looks like hanging?

**Comment by tfjmp** [comment]
Closing as the original issue seems to have been solved.
